### PR TITLE
Restore previous main colors

### PR DESCRIPTION
**Pull request by jubalh**
Some of the color changes have been very nice, the primary ones however
I don't like so much.
I have to admit that I did not come up with a nice colorscheme myself
yet, but I would like to propose to restore the old blueish colors.
Orange seems to be a bit too close to red, which just signals "something
is wrong" to me :-)

### CODE REVIEW

**Comment by jubalh** [comment]
natibo

**Comment by chickendude** [comment]
I chose orange because it's not a very common color. The previous color scheme was taken from Glossika, which i changed when the Glossika team said they'd like to distance themselves from the project. I'd also like to make this more of a general-purpose language learning app that the community can create courses for and share for free, beyond what Glossika currently offers.

I've gotten used to the orange color and have grown to really like it as it sticks out and is easy to find amongst the list of apps on my phone ;) I'm fine using a different color scheme, but not sure i want to go back to the Glossika colors. Feel free to find some colors from here:
https://www.materialui.co/colors
.. or any of the other various color tools online.

**Comment by jubalh** [comment]
So shall I close this?

**Comment by chickendude** [comment]
What would you say to maybe purple and brown? I'm fine with changing the colors, i just don't want to go back to the blue theme.

**Comment by jubalh** [comment]
Ok, when I have one I will create a new PR. Since 'restore' wont fit then anymore.

**Pull request closed without merging**
